#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: harvest-pv-claim
#  namespace: harvest
#spec:
#  storageClassName: flexvol
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harvest-app-dashboard-claim
  namespace: harvest
spec:
  storageClassName: flexvol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
