apiVersion: v1
kind: Service
metadata:
  name: harvest-app
  namespace: harvest
  labels:
    run: harvest-app
spec:
  type: NodePort
  ports:
  - port: 80
    name: graphite
    targetPort: 80
    nodePort: 32112
    protocol: TCP
  - port: 3000 
    name: grafana
    targetPort: 3000
    nodePort: 32113
    protocol: TCP
  selector:
    run: harvest-app
