apiVersion: v1
kind: ConfigMap
metadata:
  name: harvest-config
  namespace: harvest
data:
  graphite_datasource.yaml: |
          ---
          apiVersion: 1

          datasources:
            - name: Graphite
              type: graphite
              access: proxy
              url: http://localhost:80
              basicAuth: false
              isDefault: true
              jsonData:
                graphiteVersion: "1.1"

  storageschema.conf: |
    ##
    ## Dev defaults
    ##
    [netapp.perf.dev]
    pattern = ^netapp\.perf\.dev\..*
    retentions = 10s:24h, 1m:100d, 15m:395d, 1h:5y

    [netapp.poller.perf.dev]
    pattern = ^netapp\.poller\.perf\.dev\..*
    retentions = 10s:24h, 1m:100d, 15m:395d, 1h:5y

    [netapp.perf7.dev]
    pattern = ^netapp\.perf7\.dev\..*
    retentions = 10s:24h, 1m:100d, 15m:395d, 1h:5y

    [netapp.poller.perf7.dev]
    pattern = ^netapp\.poller\.perf7\.dev\..*
    retentions = 10s:24h, 1m:100d, 15m:395d, 1h:5y

    ##
    ## Prod defaults
    ##
    [OPM]
    pattern = ^netapp-performance\..*
    retentions = 5m:100d, 15m:395d, 1h:5y

    [OPM Capacity]
    pattern = ^netapp-capacity\..*
    retentions = 15m:100d, 1d:5y

    [OPM Capacity Poller]
    pattern = ^netapp-poller\..*
    retentions = 15m:100d, 1d:5y

    [netapp.capacity]
    pattern = ^netapp\.capacity\.*
    retentions = 15m:100d, 1d:5y

    [netapp.poller.capacity]
    pattern = ^netapp\.poller\.capacity\.*
    retentions = 15m:100d, 1d:5y

    [netapp.perf]
    pattern = ^netapp\.perf\.*
    retentions = 10s:14d, 60s:35d, 5m:100d, 15m:395d, 1h:5y

    [netapp.poller.perf]
    pattern = ^netapp\.poller\.perf\.*
    retentions = 10s:14d, 60s:35d, 5m:100d, 15m:395d, 1h:5y

    [netapp.perf7]
    pattern = ^netapp\.perf7\.*
    retentions = 60s:35d, 5m:100d, 15m:395d, 1h:5y

    [netapp.poller.perf7]
    pattern = ^netapp\.poller\.perf7\.*
    retentions = 60s:35d, 5m:100d, 15m:395d, 1h:5y

    ##
    ## Catch all
    ##
    [defaults]
    pattern = .*
    retentions = 10s:14d, 60s:35d, 5m:100d, 15m:395d, 1h:5y



